export enum BotEnum {
  PARTNERS_BOT = 'PARTNERS_BOT',
  FEEDBACK_BOT = 'FEEDBACK_BOT',
  ADD_MODIFICATION_BOT = 'ADD_MODIFICATION_BOT',
  SPARE_PARTS_BOT = 'SPARE_PARTS_BOT',
  CAR_ORDER_BOT = 'CAR_ORDER_BOT',
}
